---
title: "Untitled"
author: "Aina Roca"
date: "14 November 2022"
output: 
  html_document:
    theme: cerulean
    toc: yes
    toc_depth:3
    toc_float: yes
---

```{r setup, include=FALSE}

#SET THE ENVIRONMENT
rm(list=ls()) #clear the slate
.libPaths("C:/icnas1.cc.ic.ac.uk/arocabar/R/win-library/3.6") # Define location of your libraries directory
mainDir<-getwd() # Check directory is correct; otherwise set using 'setwd()'
setwd<-mainDir

#LOAD PACKAGES
library(readxl); library(ggplot2);library(plyr); library(dplyr);library(rio); library(purrr);library(RColorBrewer);library(doBy);
library(viridis);library(plyr); library(purrr);library(rio);library(gridExtra);library(seastests);library(ggridges);library(ggpmisc);
library(plotly)

#DEFINE COLORS FOR PLOTTING
greenL<-"#9FD482"; greenD<-"#308A67"; greenDD<-"#184533"; purpleL<-"#9D77C7"; purpleD<-"#56106D"; yellowL<-"#8b670f";yellowD<-"#da9f11";blueL<-"lightblue3";blueD<-"blue4";redL<-"tomato3"; redD<-"red4"
grayD<-"gray30"; grayL<-"gray70"; transparent<- adjustcolor( "red", alpha.f = 0)

#SOURCE FUNCTIONS
source('functions.R')

#0. DEFINE LISTS AND PLOTTING GROUPS
#####################################################################################################
mmtlist = list(); aflist=list(); anlist=list() # Define list to store results

#CREATE OUTCOME GROUPS& LABELS FOR PLOTTING
year<-c("2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017","2018")

out<-c("total", "females", "males", "RETI_65.79", "females_RETI_65.79", "males_RETI_65.79","RETII_.80","females_RETII_.80", "males_RETII_.80","colored", "females_colored","males_colored","white", "females_white","males_white",
       "RETI_65.79_colored","RETI_65.79_white","RETII_.80_colored" ,  "RETII_.80_white")
out1<-c("total", "females", "males", "RETI_65.79", "females_RETI_65.79", "males_RETI_65.79","RETII_.80","females_RETII_.80", "males_RETII_.80","colored", "females_colored","males_colored","white", "females_white","males_white")
out2<-c("RETI_65.79_colored","RETI_65.79_white","RETII_.80_colored" ,  "RETII_.80_white")
cause<-c("cvd", "resp")

labelsCause<-c( cvd="I. Cardiovascular diseases", resp="II. Respiratory diseases")
labels<-c(total="a. All non-external causes (all ages)", females="b. Females (all ages)", males="c. Males (all ages)", 
          RETI_65.79="d. Aged 65-79y", females_RETI_65.79="e.Females (aged 65-79y)", males_RETI_65.79="f.Males (aged 65-79y)", RETII_.80="g. Aged 80+y", 
          females_RETII_.80="h. Females (aged 80+y)", males_RETII_.80="i. Males (aged 80+y)", colored="j. Non-white (all ages)",females_colored= "k. Females non-white (all ages)",
          males_colored="l. Males Non-White (all ages)", white="m. Whites (all ages)", females_white="n. Females White (all ages)", males_white="o. Males White (all ages)",
          RETI_65.79_colored="p. Non-white (aged 65-79y)",RETI_65.79_white="q. White (aged 65-79y)",RETII_.80_colored="r. Non-white (aged 80+y)" ,  RETII_.80_white="s. White (aged 80+y)")
labels1<-c(total="A. All non-external causes (all ages)", females="B. Females (all ages)", males="C. Males (all ages)", 
           RETI_65.79="D. Aged 65-79y", females_RETI_65.79="E.Females (aged 65-79y)", males_RETI_65.79="F.Males (aged 65-79y)", RETII_.80="G. Aged 80+y", 
           females_RETII_.80="H. Females (aged 80+y)", males_RETII_.80="I. Males (aged 80+y)", colored="J. Non-white (all ages)",females_colored= "K. Females non-white (all ages)",
           males_colored="L. Males Non-White (all ages)", white="M. Whites (all ages)", females_white="N. Females White (all ages)", males_white="O. Males White (all ages)")
labels2<-c(RETI_65.79_colored="P. Non-white (aged 65-79y)",RETI_65.79_white="Q. White (aged 65-79y)",RETII_.80_colored="R. Non-white (aged 80+y)" ,  RETII_.80_white="S. White (aged 80+y)")
 

#DEFINE COLORS FOR PLOTTING
greenL<-"#9FD482"; greenD<-"#308A67"; greenDD<-"#184533"; purpleL<-"#9D77C7"; purpleD<-"#56106D"; yellowL<-"#8b670f";yellowD<-"#da9f11";blueL<-"lightblue3";blueD<-"blue4";redL<-"tomato3"; redD<-"red4"
grayD<-"gray30"; grayL<-"gray70"; transparent<- adjustcolor( "red", alpha.f = 0)

```



```{r loadData}
#LOAD FILES
rr<-read_xlsx(paste0( mainDir,"/data/RRdata_all.xlsx"))
rrINT<-read_xlsx(paste0( mainDir,"/data/RRdata_INT.xlsx"))
mmt<-read_xlsx(paste0(mainDir,"/data/summary_all_mmt_af_an.xlsx"))
temp<-read.csv(paste0(mainDir,"/data/mortality_sp_model_exploration_Nov2021.csv"))#

```

## Tempearture

```{r tempBoxPlot, echo=FALSE}
p<-ggplot(temp, aes(x=as.factor(year), y=temp_mean)) + 
  geom_violin(trim=F, fill="gray" ,col="gray50")+
  geom_boxplot(width=0.1, fill="white", col="gray50")+
  labs(title="",x="", y = "Temperature (C)")+
  geom_hline(yintercept=mean(temp$temp_mean), linetype='dashed', size=0.7, col = 'red')+
  scale_fill_manual("#E7B800") + theme_classic()
ggplotly(p)
```


```

